-- =============================================================================
-- FILE: sql/01_setup_external_volume.sql
-- PURPOSE: Create external volumes, database, schemas, and warehouses for the
--          Iceberg lakehouse migration.
-- PREREQUISITE: S3 bucket and IAM role must be created first (Terraform).
--               Run Terraform in config/terraform/ before this script.
-- EXECUTION ORDER: Run this script first, then extract IAM info for trust policy.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- STEP 0: Set context
-- -----------------------------------------------------------------------------
USE ROLE SYSADMIN;
USE WAREHOUSE ADMIN_WH;

-- -----------------------------------------------------------------------------
-- STEP 1: Create database and schemas (if not already present)
-- -----------------------------------------------------------------------------
CREATE DATABASE IF NOT EXISTS TRADE_ANALYTICS
  DATA_RETENTION_TIME_IN_DAYS = 7
  COMMENT = 'Financial services trade analytics — managed + Iceberg hybrid';

CREATE SCHEMA IF NOT EXISTS TRADE_ANALYTICS.RAW
  DATA_RETENTION_TIME_IN_DAYS = 7
  COMMENT = 'Landing zone for raw ingested trade data';

CREATE SCHEMA IF NOT EXISTS TRADE_ANALYTICS.ICEBERG
  COMMENT = 'Iceberg tables on S3 — warm and cold tier';

CREATE SCHEMA IF NOT EXISTS TRADE_ANALYTICS.MANAGED
  DATA_RETENTION_TIME_IN_DAYS = 7
  COMMENT = 'Snowflake managed tables — hot tier (<30 days)';

CREATE SCHEMA IF NOT EXISTS TRADE_ANALYTICS.VIEWS
  COMMENT = 'Unified view layer — consumed by all downstream tools';

CREATE SCHEMA IF NOT EXISTS TRADE_ANALYTICS.SNAPSHOTS
  DATA_RETENTION_TIME_IN_DAYS = 90
  COMMENT = 'Monthly point-in-time compliance snapshot tables. Retention=90 days so Time Travel works on each snapshot for 3 months after creation. Tables retained for 13 months via DROP policy in SP_MONTHLY_SNAPSHOT.';

-- -----------------------------------------------------------------------------
-- STEP 2: Create warehouses (right-sized per workload)
-- -----------------------------------------------------------------------------
-- Hot tier ingest and general queries
CREATE WAREHOUSE IF NOT EXISTS TRADE_HOT_WH
  WAREHOUSE_SIZE   = 'SMALL'
  AUTO_SUSPEND     = 60
  AUTO_RESUME      = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 3
  SCALING_POLICY   = 'ECONOMY'
  COMMENT          = 'Hot tier queries and daily ingest';

-- Cold/warm Iceberg queries (nightly risk batches, compliance reports)
CREATE WAREHOUSE IF NOT EXISTS TRADE_COLD_WH
  WAREHOUSE_SIZE   = 'MEDIUM'
  AUTO_SUSPEND     = 120
  AUTO_RESUME      = TRUE
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 2
  SCALING_POLICY   = 'ECONOMY'
  COMMENT          = 'Cold/warm Iceberg queries — risk and compliance workloads';

-- Small warehouse for ad-hoc analyst queries (cost control)
CREATE WAREHOUSE IF NOT EXISTS ANALYST_WH
  WAREHOUSE_SIZE   = 'XSMALL'
  AUTO_SUSPEND     = 60
  AUTO_RESUME      = TRUE
  COMMENT          = 'Analyst ad-hoc queries — auto-suspend aggressively';

-- Admin/migration warehouse (used during data migration only)
CREATE WAREHOUSE IF NOT EXISTS MIGRATION_WH
  WAREHOUSE_SIZE   = 'LARGE'
  AUTO_SUSPEND     = 300
  AUTO_RESUME      = TRUE
  COMMENT          = 'Used exclusively during migration windows — suspend after project';

-- -----------------------------------------------------------------------------
-- STEP 3: Create external volume (primary region — us-east-1)
-- NOTE: Replace placeholder ARN below. Procedure:
--       1. Run this CREATE with any valid ARN format first
--       2. DESCRIBE EXTERNAL VOLUME iceberg_prod_vol
--       3. Copy STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID
--       4. Update trust policy in Terraform (config/terraform/main.tf)
--       5. Re-run this CREATE OR REPLACE with the correct ARN
-- -----------------------------------------------------------------------------
CREATE OR REPLACE EXTERNAL VOLUME iceberg_prod_vol
  STORAGE_LOCATIONS = (
    (
      NAME              = 'iceberg-us-east-1'
      STORAGE_PROVIDER  = 'S3'
      STORAGE_BASE_URL  = 's3://tradeco-iceberg-prod/'
      STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::222222222222:role/snowflake-iceberg-role'
      -- STORAGE_AWS_EXTERNAL_ID is auto-generated by Snowflake; retrieved via DESCRIBE
    )
  )
  COMMENT = 'Primary Iceberg external volume — S3 us-east-1';

-- DR external volume (us-west-2) — for disaster recovery queries
CREATE OR REPLACE EXTERNAL VOLUME iceberg_dr_vol
  STORAGE_LOCATIONS = (
    (
      NAME              = 'iceberg-us-west-2'
      STORAGE_PROVIDER  = 'S3'
      STORAGE_BASE_URL  = 's3://tradeco-iceberg-dr/'
      STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::222222222222:role/snowflake-iceberg-role-dr'
    )
  )
  COMMENT = 'DR Iceberg external volume — S3 us-west-2';

-- -----------------------------------------------------------------------------
-- STEP 4: Retrieve IAM principal info (CRITICAL — do this before continuing)
-- Copy the STORAGE_AWS_IAM_USER_ARN and STORAGE_AWS_EXTERNAL_ID values.
-- These go into the IAM role trust policy in Terraform.
-- -----------------------------------------------------------------------------
DESCRIBE EXTERNAL VOLUME iceberg_prod_vol;
/*
Expected output columns (relevant):
  PROPERTY                        | PROPERTY_VALUE
  STORAGE_AWS_IAM_USER_ARN        | arn:aws:iam::123456789999:user/snowflake-iam-user-abc123
  STORAGE_AWS_EXTERNAL_ID         | ABC123XYZ_SFCRole=2_xxx/yyy
  
Paste these values into config/terraform/variables.tf:
  snowflake_iam_user_arn   = "arn:aws:iam::123456789999:user/snowflake-iam-user-abc123"
  snowflake_external_id    = "ABC123XYZ_SFCRole=2_xxx/yyy"

Then re-run Terraform to update the trust policy on the IAM role.
Then re-run STEP 3 above with the correct ARN.
*/

-- -----------------------------------------------------------------------------
-- STEP 5: Validate external volume connectivity
-- Run this ONLY after Terraform trust policy has been applied.
-- A successful result (no error) confirms Snowflake can reach S3.
-- -----------------------------------------------------------------------------
USE SCHEMA TRADE_ANALYTICS.ICEBERG;

CREATE OR REPLACE TEMPORARY STAGE iceberg_connectivity_test
  EXTERNAL_VOLUME = iceberg_prod_vol
  DIRECTORY = (ENABLE = FALSE);
-- If this succeeds: external volume is correctly configured.
-- Drop the test stage immediately.
DROP STAGE iceberg_connectivity_test;

-- -----------------------------------------------------------------------------
-- STEP 6: Grant privileges
-- -----------------------------------------------------------------------------
USE ROLE SECURITYADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS ICEBERG_ADMIN   COMMENT = 'Full DDL and DML on Iceberg tables';
CREATE ROLE IF NOT EXISTS ICEBERG_READER  COMMENT = 'Read-only access to Iceberg tables and views';
CREATE ROLE IF NOT EXISTS MIGRATION_ROLE  COMMENT = 'Used during migration — DROP after project';

-- Grant external volume usage
GRANT USAGE ON EXTERNAL VOLUME iceberg_prod_vol TO ROLE ICEBERG_ADMIN;
GRANT USAGE ON EXTERNAL VOLUME iceberg_prod_vol TO ROLE MIGRATION_ROLE;

-- Grant database/schema access
GRANT USAGE ON DATABASE TRADE_ANALYTICS TO ROLE ICEBERG_ADMIN;
GRANT USAGE ON DATABASE TRADE_ANALYTICS TO ROLE ICEBERG_READER;

GRANT ALL ON SCHEMA TRADE_ANALYTICS.ICEBERG   TO ROLE ICEBERG_ADMIN;
GRANT ALL ON SCHEMA TRADE_ANALYTICS.SNAPSHOTS TO ROLE ICEBERG_ADMIN;
GRANT ALL ON SCHEMA TRADE_ANALYTICS.VIEWS     TO ROLE ICEBERG_ADMIN;
GRANT USAGE ON SCHEMA TRADE_ANALYTICS.ICEBERG TO ROLE ICEBERG_READER;
GRANT USAGE ON SCHEMA TRADE_ANALYTICS.VIEWS   TO ROLE ICEBERG_READER;

GRANT USAGE  ON WAREHOUSE TRADE_COLD_WH TO ROLE ICEBERG_ADMIN;
GRANT USAGE  ON WAREHOUSE TRADE_COLD_WH TO ROLE ICEBERG_READER;
GRANT USAGE  ON WAREHOUSE ANALYST_WH    TO ROLE ICEBERG_READER;
GRANT USAGE  ON WAREHOUSE MIGRATION_WH  TO ROLE MIGRATION_ROLE;

-- Grant migration role access to source managed schema
GRANT USAGE    ON SCHEMA TRADE_ANALYTICS.MANAGED TO ROLE MIGRATION_ROLE;
GRANT SELECT   ON ALL TABLES IN SCHEMA TRADE_ANALYTICS.MANAGED TO ROLE MIGRATION_ROLE;
GRANT INSERT   ON ALL TABLES IN SCHEMA TRADE_ANALYTICS.ICEBERG  TO ROLE MIGRATION_ROLE;

-- Assign roles to SYSADMIN hierarchy
GRANT ROLE ICEBERG_ADMIN  TO ROLE SYSADMIN;
GRANT ROLE ICEBERG_READER TO ROLE SYSADMIN;
GRANT ROLE MIGRATION_ROLE TO ROLE SYSADMIN;

-- -----------------------------------------------------------------------------
-- STEP 7: Create MIGRATION_LOG audit table
-- NOTE: Moved here from sql/03_migrate_data.sql — this table must exist
--       BEFORE migrate_table.sh runs. Running 03 before 01 caused errors.
-- -----------------------------------------------------------------------------
USE ROLE MIGRATION_ROLE;

CREATE TABLE IF NOT EXISTS TRADE_ANALYTICS.MANAGED.MIGRATION_LOG (
    migration_run_id  VARCHAR(36)    DEFAULT UUID_STRING() NOT NULL,
    source_table      VARCHAR(200)   NOT NULL,
    target_table      VARCHAR(200)   NOT NULL,
    partition_start   DATE           NOT NULL,
    partition_end     DATE           NOT NULL,
    rows_migrated     NUMBER(20,0)   NOT NULL,
    migration_ts      TIMESTAMP_NTZ  DEFAULT CURRENT_TIMESTAMP(),
    status            VARCHAR(20)    DEFAULT 'COMPLETED',
    notes             VARCHAR(2000),
    CONSTRAINT pk_migration_log PRIMARY KEY (migration_run_id)
)
DATA_RETENTION_TIME_IN_DAYS = 90
COMMENT = 'Audit log: one row per migrated month-partition.';

GRANT SELECT, INSERT ON TABLE TRADE_ANALYTICS.MANAGED.MIGRATION_LOG
    TO ROLE MIGRATION_ROLE;
GRANT SELECT ON TABLE TRADE_ANALYTICS.MANAGED.MIGRATION_LOG
    TO ROLE ICEBERG_READER;

-- =============================================================================
-- END OF SCRIPT 01
-- NEXT: Run sql/02_create_iceberg_tables.sql
-- =============================================================================